function loadData(attempts,simtime,loop,handles,timeperpanel,compTime)

handles.trialText.String = num2str(size(attempts,1));
i = str2double(handles.trialText.String);

avetimeperpanel = [sum(timeperpanel(:,1,1))/i,...
    sum(timeperpanel(:,2,1))/i, ...
    sum(timeperpanel(:,3,1))/i; ...
    sum(timeperpanel(:,1,2))/i, ...
    sum(timeperpanel(:,2,2))/i, ...
    sum(timeperpanel(:,3,2))/i; ...
    sum(timeperpanel(:,1,3))/i, ...
    sum(timeperpanel(:,2,3))/i, ...
    sum(timeperpanel(:,3,3))/i; ...
    sum(timeperpanel(:,1,4))/i, ...
    sum(timeperpanel(:,2,4))/i, ...
    sum(timeperpanel(:,3,4))/i; ...
    sum(sum(timeperpanel(:,1,1:4)))/i, ...
    sum(sum(timeperpanel(:,2,1:4)))/i, ...
    sum(sum(timeperpanel(:,3,1:4)))/i];

handles.aveRandText.String = num2str(sum(sum(timeperpanel(:,1,1:4)))/i);
handles.aveBruteText.String = num2str(sum(sum(timeperpanel(:,2,1:4)))/i);
handles.aveRuleText.String = num2str(sum(sum(timeperpanel(:,3,1:4)))/i);

handles.failedRandText.String = num2str(sum(attempts(:,1)));
handles.failedBruteText.String = num2str(sum(attempts(:,2)));

aveCompTime = [sum(compTime(:,1))/i,sum(compTime(:,2))/i,sum(compTime(:,3))/i];
handles.randCompT.String = num2str(aveCompTime(1));
handles.bruteCompT.String = num2str(aveCompTime(2));
handles.ruleCompT.String = num2str(aveCompTime(3));

bar(handles.resultAxes,avetimeperpanel);
grid(handles.resultAxes,'on');
ylabel('Simulated time to complete task (s)');
set(gca,'xticklabel',{'Wires','Switches','Buttons','Numpad','Total Time'});
legend(handles.resultAxes,'Randomizer','Brute Force','Rule Abider','Location','Northwest');